#!/bin/bash

PREFIX='/usr'

if [[ $1 == "--user" || $2 == "--user" ]]; then
    PREFIX="$HOME/.local"
fi


if [[ $1 == "--uninstall" || $2 == "--uninstall" ]]
then
    if [ -f  $PREFIX/bin/rstream ] && [ -f $PREFIX/bin/mappings.py ]
    then
        echo "Removing files ...."
        sudo rm -f $PREFIX/bin/rstream $PREFIX/bin/mappings.py $PREFIX/bin/rstream-init 
        rm -rf ~/.config/rstream
        echo "Uninstallation Complete"
    else
    	echo "Not Installed"
    fi 
    

elif [ -f  $PREFIX/bin/rstream ] && [ -f $PREFIX/bin/mappings.py ];  then
    echo "Already Installed"
else
    echo "Copying required files and setting up audio modules...."
    sudo cp rstream mappings.py rstream-init $PREFIX/bin
    mkdir -p ~/.config/rstream
    cp .stream_config.json ~/.config/rstream
    echo "Installation Complete"
    
fi
