#!/bin/bash

Sink='alsa_output.pci-0000_00_1f.3.analog-stereo'
Source='alsa_input.pci-0000_00_1f.3.analog-stereo'

if [ $# -eq 0 ]; then

	
    pactl load-module module-null-sink sink_name=V1
    pactl load-module module-null-sink sink_name=V2

    pactl load-module module-loopback source=$Source sink=V1
    pactl load-module module-loopback source=V2.monitor sink=V1
 	pactl load-module module-loopback source=V2.monitor sink=$Sink
 	echo "Now You are ready to stream . Run the rstream command to start streaming ...."
else
    systemctl --user restart pulseaudio
fi
